[misc]
generated = true # REMOVE THIS TO START USING THIS FILE

[upgrade.install]
packages = [
    'a',
    'b',
    { name = 'c', idk = true, url = 'idk', etc = true }
]

[upgrade.ignore]
packages = []
